### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by GregoryAshton** [mfouesneau/NUTS#3]
Hi,

I'd like to try this package out and compare it to things like `emcee`. However, there is no installation instructions. Ideally, a setup.py or pip installable would be great. Would you be able to add this at all?

Best,

Greg

**Comment by mfouesneau** [comment]
Done. You can pip install it.

**Comment by jelc53** [comment]
There is another package that is installed when I run "pip install nuts" (https://pypi.org/project/nuts/). How do I install this package and not the other?

**Comment by mfouesneau** [comment]
this package is not on pypi. If this is a request I could port it there. But you can install it with
```pip install git+https://github.com/mfouesneau/NUTS```
