### ISSUE TITLE
Is it mandatory to define a gradient function?

### ISSUE THREAD

**Issue by Gabriel-p** [mfouesneau/NUTS#4]
I want to use this package as an `emcee` sampler, but if possible I'd like to avoid having to define the gradient for the log-likelihood.

I know this is possible with the [sampyl](https://github.com/mcleonard/sampyl) package, which uses `autograd` to do it, but I'm not sure if this package does something similar. The README says about the grad function: "*if not numerical estimates are made, but slower*", but nothing else.

Can I not define a gradient function? If so, how does NUTS handle this?

Thank you!

**Comment by mfouesneau** [comment]
NUTS is a refined hamiltonian MCMC sampler. Hence, it is necessary to define a gradient function to use this sampler. 
You can use the numerical gradient function in the `helpers` I provide, but that has a cost.
You can use the emcee_nuts class which will use it directly if you don't provide a gradient function.

But my version of gradient implementation is very simple and expensive.

**Comment by Gabriel-p** [comment]
Thank you for the clarification Morgan!
