### ISSUE TITLE
A question about a line of code in the function of find_reasonable_epsilon.

### ISSUE THREAD

**Issue by shijunVV** [mfouesneau/NUTS#7]
Thank you for publishing this nice code as it is really helpful for beginners like me to learn the NUTS in detail.

I got a question about a line of code when I was going through the source code.

> k = 1.
   > while np.isinf(logpprime) or np.isinf(gradprime).any():
         k *= 0.5
         _, rprime, _, logpprime = leapfrog(theta0, r0, grad0, epsilon * k, f)

Apparently, the ***gradprime*** in the loop statement was not updated at all, which possibly causes a dead loop. So I wonder if it was a typo or I misunderstood something about this part of code?

**Comment by mfouesneau** [comment]
it a bit far, but I believe it is only to initialize the work. gradient remains the same at the current location.

-- I could be wrong though

**Comment by shijunVV** [comment]
> it a bit far, but I believe it is only to initialize the work. gradient remains the same at the current location.
> 
> -- I could be wrong though

Thank you for explanation.

**Comment by mfouesneau** [comment]
If you have more on this, happy to dig more. (closing in the meantime)
